<?php include __DIR__ . '/../header.html' ?>
    <div class="container">
        <div class="row">
            <h3>Post List</h3>
            <a class="btn btn-primary btn-sm" href="/posts/create">New post</a>
            <table class="table">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($posts as $post): ?>
                    <tr>
                        <td><?php echo $post->getId(); ?></td>
                        <td><?php echo $post->getTitle(); ?></td>
                        <td>
                            <?php echo "<a class='btn btn-primary btn-xs'
                                           href='/posts/{$post->getId()}/categories'>Categories</a>"; ?>
                            <?php echo "<a class='btn btn-primary btn-xs'
                                           href='/posts/{$post->getId()}/edit'>Edit</a>"; ?>
                            <?php echo "<a class='btn btn-danger btn-xs'
                                           href='/posts/{$post->getId()}/remove'>Delete</a>"; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
<?php include __DIR__ . '/../footer.html' ?>